install.packages(lmtest)
library(lmtest)
data=data10
colnames(data)=c('total','population','GDP','GDP.per.cap','mortality','internet','area','life.expt','secondary','primary','sex')
attach(data)
View(data)
cor(data,use = 'pairwise.complete.obs')
summary(data)

par(mfrow=c(1,2))
plot(area,total)
plot(GDP,total)

model1=lm(total~population+GDP+mortality+internet+area+life.expt+secondary+primary)
summary(model1)
dwtest(model1)
model2=lm(total~GDP+area+life.expt+primary)
summary(model2)
anova(model1,model2)
plot(model1)
plot(model2)